name: Karen YouTube

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "YouTube URL"
        required: true
      quality:
        description: "Video Quality (e.g. 144, 240, 360, 480)"
        required: true
        default: "360"
      password:
        description: "Optional password (leave empty if not needed)"
        required: false
        
jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y ffmpeg aria2
          python3 -m pip install -U yt-dlp
          
